### ISSUE TITLE
"The person's name was empty or null. "

### ISSUE THREAD

**Issue by vBm** [jellyfin/jellyfin-plugin-omdb#1]
Edit: Running 10.7 RC1 in portable mode on Windows 10.

Error appeared once it started scanning [Tajkun](https://www.imdb.com/title/tt10927414/) TV Show
```
[06:40:58] [ERR] [34] MediaBrowser.Providers.TV.SeriesMetadataService: Error in The Open Movie Database
System.ArgumentException: The person's name was empty or null. (Parameter 'person')
   at MediaBrowser.Controller.Entities.PeopleHelper.AddPerson(List`1 people, PersonInfo person)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.ParseAdditionalMetadata[T](MetadataResult`1 itemResult, RootObject result)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.Fetch[T](MetadataResult`1 itemResult, String imdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
I wasn't able to reproduce this when I just tested, hopefully my change will solve the issue in RC2

**Comment by vBm** [comment]
Since i don't get it anymore on RC2 it's safe to say that you did fix it 👍 Thanks for that 
Can be closed.
